package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CapituloBibliaCacheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapituloBibliaCacheAllPropertiesEquals(CapituloBibliaCache expected, CapituloBibliaCache actual) {
        assertCapituloBibliaCacheAutoGeneratedPropertiesEquals(expected, actual);
        assertCapituloBibliaCacheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapituloBibliaCacheAllUpdatablePropertiesEquals(CapituloBibliaCache expected, CapituloBibliaCache actual) {
        assertCapituloBibliaCacheUpdatableFieldsEquals(expected, actual);
        assertCapituloBibliaCacheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapituloBibliaCacheAutoGeneratedPropertiesEquals(CapituloBibliaCache expected, CapituloBibliaCache actual) {
        assertThat(actual)
            .as("Verify CapituloBibliaCache auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapituloBibliaCacheUpdatableFieldsEquals(CapituloBibliaCache expected, CapituloBibliaCache actual) {
        assertThat(actual)
            .as("Verify CapituloBibliaCache relevant properties")
            .satisfies(a -> assertThat(a.getLivroId()).as("check livroId").isEqualTo(expected.getLivroId()))
            .satisfies(a -> assertThat(a.getLivroNome()).as("check livroNome").isEqualTo(expected.getLivroNome()))
            .satisfies(a -> assertThat(a.getCapitulo()).as("check capitulo").isEqualTo(expected.getCapitulo()))
            .satisfies(a -> assertThat(a.getVersao()).as("check versao").isEqualTo(expected.getVersao()))
            .satisfies(a -> assertThat(a.getVersiculosJson()).as("check versiculosJson").isEqualTo(expected.getVersiculosJson()))
            .satisfies(a -> assertThat(a.getCacheadoEm()).as("check cacheadoEm").isEqualTo(expected.getCacheadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapituloBibliaCacheUpdatableRelationshipsEquals(CapituloBibliaCache expected, CapituloBibliaCache actual) {
        // empty method
    }
}
