package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DestaqueBibliaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDestaqueBibliaAllPropertiesEquals(DestaqueBiblia expected, DestaqueBiblia actual) {
        assertDestaqueBibliaAutoGeneratedPropertiesEquals(expected, actual);
        assertDestaqueBibliaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDestaqueBibliaAllUpdatablePropertiesEquals(DestaqueBiblia expected, DestaqueBiblia actual) {
        assertDestaqueBibliaUpdatableFieldsEquals(expected, actual);
        assertDestaqueBibliaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDestaqueBibliaAutoGeneratedPropertiesEquals(DestaqueBiblia expected, DestaqueBiblia actual) {
        assertThat(actual)
            .as("Verify DestaqueBiblia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDestaqueBibliaUpdatableFieldsEquals(DestaqueBiblia expected, DestaqueBiblia actual) {
        assertThat(actual)
            .as("Verify DestaqueBiblia relevant properties")
            .satisfies(a -> assertThat(a.getChaveReferencia()).as("check chaveReferencia").isEqualTo(expected.getChaveReferencia()))
            .satisfies(a -> assertThat(a.getLivroId()).as("check livroId").isEqualTo(expected.getLivroId()))
            .satisfies(a -> assertThat(a.getLivroNome()).as("check livroNome").isEqualTo(expected.getLivroNome()))
            .satisfies(a -> assertThat(a.getCapitulo()).as("check capitulo").isEqualTo(expected.getCapitulo()))
            .satisfies(a -> assertThat(a.getVersiculoInicio()).as("check versiculoInicio").isEqualTo(expected.getVersiculoInicio()))
            .satisfies(a -> assertThat(a.getVersiculoFim()).as("check versiculoFim").isEqualTo(expected.getVersiculoFim()))
            .satisfies(a -> assertThat(a.getVersao()).as("check versao").isEqualTo(expected.getVersao()))
            .satisfies(a -> assertThat(a.getCor()).as("check cor").isEqualTo(expected.getCor()))
            .satisfies(a -> assertThat(a.getCriadoEm()).as("check criadoEm").isEqualTo(expected.getCriadoEm()))
            .satisfies(a -> assertThat(a.getAtualizadoEm()).as("check atualizadoEm").isEqualTo(expected.getAtualizadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDestaqueBibliaUpdatableRelationshipsEquals(DestaqueBiblia expected, DestaqueBiblia actual) {
        // empty method
    }
}
