package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiaPlanoLeituraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiaPlanoLeituraAllPropertiesEquals(DiaPlanoLeitura expected, DiaPlanoLeitura actual) {
        assertDiaPlanoLeituraAutoGeneratedPropertiesEquals(expected, actual);
        assertDiaPlanoLeituraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiaPlanoLeituraAllUpdatablePropertiesEquals(DiaPlanoLeitura expected, DiaPlanoLeitura actual) {
        assertDiaPlanoLeituraUpdatableFieldsEquals(expected, actual);
        assertDiaPlanoLeituraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiaPlanoLeituraAutoGeneratedPropertiesEquals(DiaPlanoLeitura expected, DiaPlanoLeitura actual) {
        assertThat(actual)
            .as("Verify DiaPlanoLeitura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiaPlanoLeituraUpdatableFieldsEquals(DiaPlanoLeitura expected, DiaPlanoLeitura actual) {
        assertThat(actual)
            .as("Verify DiaPlanoLeitura relevant properties")
            .satisfies(a -> assertThat(a.getNumeroDia()).as("check numeroDia").isEqualTo(expected.getNumeroDia()))
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getLeiturasJson()).as("check leiturasJson").isEqualTo(expected.getLeiturasJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiaPlanoLeituraUpdatableRelationshipsEquals(DiaPlanoLeitura expected, DiaPlanoLeitura actual) {
        assertThat(actual)
            .as("Verify DiaPlanoLeitura relationships")
            .satisfies(a -> assertThat(a.getPlano()).as("check plano").isEqualTo(expected.getPlano()))
            .satisfies(a -> assertThat(a.getPlanoLeitura()).as("check planoLeitura").isEqualTo(expected.getPlanoLeitura()));
    }
}
