package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnderecoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoAllPropertiesEquals(Endereco expected, Endereco actual) {
        assertEnderecoAutoGeneratedPropertiesEquals(expected, actual);
        assertEnderecoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoAllUpdatablePropertiesEquals(Endereco expected, Endereco actual) {
        assertEnderecoUpdatableFieldsEquals(expected, actual);
        assertEnderecoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoAutoGeneratedPropertiesEquals(Endereco expected, Endereco actual) {
        assertThat(actual)
            .as("Verify Endereco auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoUpdatableFieldsEquals(Endereco expected, Endereco actual) {
        assertThat(actual)
            .as("Verify Endereco relevant properties")
            .satisfies(a -> assertThat(a.getLogradouro()).as("check logradouro").isEqualTo(expected.getLogradouro()))
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getComplemento()).as("check complemento").isEqualTo(expected.getComplemento()))
            .satisfies(a -> assertThat(a.getBairro()).as("check bairro").isEqualTo(expected.getBairro()))
            .satisfies(a -> assertThat(a.getCidade()).as("check cidade").isEqualTo(expected.getCidade()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getCep()).as("check cep").isEqualTo(expected.getCep()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoUpdatableRelationshipsEquals(Endereco expected, Endereco actual) {
        // empty method
    }
}
