package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FavoritoBibliaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoritoBibliaAllPropertiesEquals(FavoritoBiblia expected, FavoritoBiblia actual) {
        assertFavoritoBibliaAutoGeneratedPropertiesEquals(expected, actual);
        assertFavoritoBibliaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoritoBibliaAllUpdatablePropertiesEquals(FavoritoBiblia expected, FavoritoBiblia actual) {
        assertFavoritoBibliaUpdatableFieldsEquals(expected, actual);
        assertFavoritoBibliaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoritoBibliaAutoGeneratedPropertiesEquals(FavoritoBiblia expected, FavoritoBiblia actual) {
        assertThat(actual)
            .as("Verify FavoritoBiblia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoritoBibliaUpdatableFieldsEquals(FavoritoBiblia expected, FavoritoBiblia actual) {
        assertThat(actual)
            .as("Verify FavoritoBiblia relevant properties")
            .satisfies(a -> assertThat(a.getChaveReferencia()).as("check chaveReferencia").isEqualTo(expected.getChaveReferencia()))
            .satisfies(a -> assertThat(a.getLivroId()).as("check livroId").isEqualTo(expected.getLivroId()))
            .satisfies(a -> assertThat(a.getLivroNome()).as("check livroNome").isEqualTo(expected.getLivroNome()))
            .satisfies(a -> assertThat(a.getCapitulo()).as("check capitulo").isEqualTo(expected.getCapitulo()))
            .satisfies(a -> assertThat(a.getVersiculoInicio()).as("check versiculoInicio").isEqualTo(expected.getVersiculoInicio()))
            .satisfies(a -> assertThat(a.getVersiculoFim()).as("check versiculoFim").isEqualTo(expected.getVersiculoFim()))
            .satisfies(a -> assertThat(a.getVersao()).as("check versao").isEqualTo(expected.getVersao()))
            .satisfies(a -> assertThat(a.getCriadoEm()).as("check criadoEm").isEqualTo(expected.getCriadoEm()))
            .satisfies(a -> assertThat(a.getAtualizadoEm()).as("check atualizadoEm").isEqualTo(expected.getAtualizadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoritoBibliaUpdatableRelationshipsEquals(FavoritoBiblia expected, FavoritoBiblia actual) {
        // empty method
    }
}
