package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoricoLeituraBibliaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoLeituraBibliaAllPropertiesEquals(HistoricoLeituraBiblia expected, HistoricoLeituraBiblia actual) {
        assertHistoricoLeituraBibliaAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoricoLeituraBibliaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoLeituraBibliaAllUpdatablePropertiesEquals(
        HistoricoLeituraBiblia expected,
        HistoricoLeituraBiblia actual
    ) {
        assertHistoricoLeituraBibliaUpdatableFieldsEquals(expected, actual);
        assertHistoricoLeituraBibliaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoLeituraBibliaAutoGeneratedPropertiesEquals(
        HistoricoLeituraBiblia expected,
        HistoricoLeituraBiblia actual
    ) {
        assertThat(actual)
            .as("Verify HistoricoLeituraBiblia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoLeituraBibliaUpdatableFieldsEquals(HistoricoLeituraBiblia expected, HistoricoLeituraBiblia actual) {
        assertThat(actual)
            .as("Verify HistoricoLeituraBiblia relevant properties")
            .satisfies(a -> assertThat(a.getLivroId()).as("check livroId").isEqualTo(expected.getLivroId()))
            .satisfies(a -> assertThat(a.getLivroNome()).as("check livroNome").isEqualTo(expected.getLivroNome()))
            .satisfies(a -> assertThat(a.getCapitulo()).as("check capitulo").isEqualTo(expected.getCapitulo()))
            .satisfies(a -> assertThat(a.getVersiculoInicio()).as("check versiculoInicio").isEqualTo(expected.getVersiculoInicio()))
            .satisfies(a -> assertThat(a.getVersiculoFim()).as("check versiculoFim").isEqualTo(expected.getVersiculoFim()))
            .satisfies(a -> assertThat(a.getVersao()).as("check versao").isEqualTo(expected.getVersao()))
            .satisfies(a -> assertThat(a.getLidoEm()).as("check lidoEm").isEqualTo(expected.getLidoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoricoLeituraBibliaUpdatableRelationshipsEquals(
        HistoricoLeituraBiblia expected,
        HistoricoLeituraBiblia actual
    ) {
        // empty method
    }
}
