package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlanoLeituraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoLeituraAllPropertiesEquals(PlanoLeitura expected, PlanoLeitura actual) {
        assertPlanoLeituraAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanoLeituraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoLeituraAllUpdatablePropertiesEquals(PlanoLeitura expected, PlanoLeitura actual) {
        assertPlanoLeituraUpdatableFieldsEquals(expected, actual);
        assertPlanoLeituraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoLeituraAutoGeneratedPropertiesEquals(PlanoLeitura expected, PlanoLeitura actual) {
        assertThat(actual)
            .as("Verify PlanoLeitura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoLeituraUpdatableFieldsEquals(PlanoLeitura expected, PlanoLeitura actual) {
        assertThat(actual)
            .as("Verify PlanoLeitura relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getAtivo()).as("check ativo").isEqualTo(expected.getAtivo()))
            .satisfies(a -> assertThat(a.getCriadoEm()).as("check criadoEm").isEqualTo(expected.getCriadoEm()))
            .satisfies(a -> assertThat(a.getAtualizadoEm()).as("check atualizadoEm").isEqualTo(expected.getAtualizadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanoLeituraUpdatableRelationshipsEquals(PlanoLeitura expected, PlanoLeitura actual) {
        // empty method
    }
}
