package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PreCadastroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreCadastroAllPropertiesEquals(PreCadastro expected, PreCadastro actual) {
        assertPreCadastroAutoGeneratedPropertiesEquals(expected, actual);
        assertPreCadastroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreCadastroAllUpdatablePropertiesEquals(PreCadastro expected, PreCadastro actual) {
        assertPreCadastroUpdatableFieldsEquals(expected, actual);
        assertPreCadastroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreCadastroAutoGeneratedPropertiesEquals(PreCadastro expected, PreCadastro actual) {
        assertThat(actual)
            .as("Verify PreCadastro auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreCadastroUpdatableFieldsEquals(PreCadastro expected, PreCadastro actual) {
        assertThat(actual)
            .as("Verify PreCadastro relevant properties")
            .satisfies(a -> assertThat(a.getNomeCompleto()).as("check nomeCompleto").isEqualTo(expected.getNomeCompleto()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefone()).as("check telefone").isEqualTo(expected.getTelefone()))
            .satisfies(a -> assertThat(a.getTelefoneSecundario()).as("check telefoneSecundario").isEqualTo(expected.getTelefoneSecundario())
            )
            .satisfies(a -> assertThat(a.getTelefoneEmergencia()).as("check telefoneEmergencia").isEqualTo(expected.getTelefoneEmergencia())
            )
            .satisfies(a ->
                assertThat(a.getNomeContatoEmergencia()).as("check nomeContatoEmergencia").isEqualTo(expected.getNomeContatoEmergencia())
            )
            .satisfies(a -> assertThat(a.getCpf()).as("check cpf").isEqualTo(expected.getCpf()))
            .satisfies(a -> assertThat(a.getSexo()).as("check sexo").isEqualTo(expected.getSexo()))
            .satisfies(a -> assertThat(a.getDataNascimento()).as("check dataNascimento").isEqualTo(expected.getDataNascimento()))
            .satisfies(a -> assertThat(a.getLogin()).as("check login").isEqualTo(expected.getLogin()))
            .satisfies(a -> assertThat(a.getSenha()).as("check senha").isEqualTo(expected.getSenha()))
            .satisfies(a -> assertThat(a.getPerfilSolicitado()).as("check perfilSolicitado").isEqualTo(expected.getPerfilSolicitado()))
            .satisfies(a -> assertThat(a.getPerfilAprovado()).as("check perfilAprovado").isEqualTo(expected.getPerfilAprovado()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getObservacoes()).as("check observacoes").isEqualTo(expected.getObservacoes()))
            .satisfies(a -> assertThat(a.getCriadoEm()).as("check criadoEm").isEqualTo(expected.getCriadoEm()))
            .satisfies(a -> assertThat(a.getAtualizadoEm()).as("check atualizadoEm").isEqualTo(expected.getAtualizadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreCadastroUpdatableRelationshipsEquals(PreCadastro expected, PreCadastro actual) {
        assertThat(actual)
            .as("Verify PreCadastro relationships")
            .satisfies(a -> assertThat(a.getEndereco()).as("check endereco").isEqualTo(expected.getEndereco()));
    }
}
