package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PreferenciaBibliaUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreferenciaBibliaUsuarioAllPropertiesEquals(
        PreferenciaBibliaUsuario expected,
        PreferenciaBibliaUsuario actual
    ) {
        assertPreferenciaBibliaUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertPreferenciaBibliaUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreferenciaBibliaUsuarioAllUpdatablePropertiesEquals(
        PreferenciaBibliaUsuario expected,
        PreferenciaBibliaUsuario actual
    ) {
        assertPreferenciaBibliaUsuarioUpdatableFieldsEquals(expected, actual);
        assertPreferenciaBibliaUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreferenciaBibliaUsuarioAutoGeneratedPropertiesEquals(
        PreferenciaBibliaUsuario expected,
        PreferenciaBibliaUsuario actual
    ) {
        assertThat(actual)
            .as("Verify PreferenciaBibliaUsuario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreferenciaBibliaUsuarioUpdatableFieldsEquals(
        PreferenciaBibliaUsuario expected,
        PreferenciaBibliaUsuario actual
    ) {
        assertThat(actual)
            .as("Verify PreferenciaBibliaUsuario relevant properties")
            .satisfies(a -> assertThat(a.getModo()).as("check modo").isEqualTo(expected.getModo()))
            .satisfies(a -> assertThat(a.getTamanhoFonte()).as("check tamanhoFonte").isEqualTo(expected.getTamanhoFonte()))
            .satisfies(a -> assertThat(a.getTema()).as("check tema").isEqualTo(expected.getTema()))
            .satisfies(a -> assertThat(a.getMostrarDestaques()).as("check mostrarDestaques").isEqualTo(expected.getMostrarDestaques()))
            .satisfies(a -> assertThat(a.getMostrarNotas()).as("check mostrarNotas").isEqualTo(expected.getMostrarNotas()))
            .satisfies(a -> assertThat(a.getMostrarFavoritos()).as("check mostrarFavoritos").isEqualTo(expected.getMostrarFavoritos()))
            .satisfies(a -> assertThat(a.getCriadoEm()).as("check criadoEm").isEqualTo(expected.getCriadoEm()))
            .satisfies(a -> assertThat(a.getAtualizadoEm()).as("check atualizadoEm").isEqualTo(expected.getAtualizadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPreferenciaBibliaUsuarioUpdatableRelationshipsEquals(
        PreferenciaBibliaUsuario expected,
        PreferenciaBibliaUsuario actual
    ) {
        // empty method
    }
}
