package br.com.semear.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProgressoLeituraUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressoLeituraUsuarioAllPropertiesEquals(ProgressoLeituraUsuario expected, ProgressoLeituraUsuario actual) {
        assertProgressoLeituraUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertProgressoLeituraUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressoLeituraUsuarioAllUpdatablePropertiesEquals(
        ProgressoLeituraUsuario expected,
        ProgressoLeituraUsuario actual
    ) {
        assertProgressoLeituraUsuarioUpdatableFieldsEquals(expected, actual);
        assertProgressoLeituraUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressoLeituraUsuarioAutoGeneratedPropertiesEquals(
        ProgressoLeituraUsuario expected,
        ProgressoLeituraUsuario actual
    ) {
        assertThat(actual)
            .as("Verify ProgressoLeituraUsuario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressoLeituraUsuarioUpdatableFieldsEquals(
        ProgressoLeituraUsuario expected,
        ProgressoLeituraUsuario actual
    ) {
        assertThat(actual)
            .as("Verify ProgressoLeituraUsuario relevant properties")
            .satisfies(a -> assertThat(a.getData()).as("check data").isEqualTo(expected.getData()))
            .satisfies(a -> assertThat(a.getConcluido()).as("check concluido").isEqualTo(expected.getConcluido()))
            .satisfies(a -> assertThat(a.getConcluidoEm()).as("check concluidoEm").isEqualTo(expected.getConcluidoEm()))
            .satisfies(a -> assertThat(a.getCriadoEm()).as("check criadoEm").isEqualTo(expected.getCriadoEm()))
            .satisfies(a -> assertThat(a.getAtualizadoEm()).as("check atualizadoEm").isEqualTo(expected.getAtualizadoEm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressoLeituraUsuarioUpdatableRelationshipsEquals(
        ProgressoLeituraUsuario expected,
        ProgressoLeituraUsuario actual
    ) {
        assertThat(actual)
            .as("Verify ProgressoLeituraUsuario relationships")
            .satisfies(a -> assertThat(a.getPlano()).as("check plano").isEqualTo(expected.getPlano()))
            .satisfies(a -> assertThat(a.getDia()).as("check dia").isEqualTo(expected.getDia()));
    }
}
