export {
  type ComunicadoDTO as InformativoDTO,
  type ComunicadoLeituraDTO as InformativoLeituraDTO,
  type TipoComunicadoApi as TipoInformativoApi,
  type PublicoAlvoComunicadoApi as PublicoAlvoInformativoApi,
  type PrioridadeComunicadoApi as PrioridadeInformativoApi,
  LABEL_PUBLICO,
  LABEL_TIPO,
  listarComunicados as listarInformativosAdmin,
  listarComunicadosPendentesLogin as listarInformativosPendentesLogin,
  listarComunicadosBanner as listarInformativosBanner,
  criarComunicado as criarInformativo,
  atualizarComunicado as atualizarInformativo,
  excluirComunicado as excluirInformativo,
  confirmarComunicado as confirmarInformativo,
  listarLeiturasComunicado as listarLeiturasInformativo,
} from "@/modules/comunicados/api";
